server.port=8080
spring.application.name=geradornotafiscal

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.health.defaults.enabled=true

logging.level.root=INFO
logging.level.br.com.itau.geradornotafiscal=INFO
